server:
  port: 8080
spring:
  jackson:
    time-zone: Asia/Shanghai
  mvc:
    view:
      prefix: /WEB-INF/views/
      suffix: .jsp
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/HRM?useUnicode=true&characterEncoding=utf-8&serverTimezone=UTC
    username: root  #用自己的
    password: 7301263.. #用自己的
mybatis-plus:
  type-aliases-package: com.example.pojo      # POJO 类的包
  configuration:
    map-underscore-to-camel-case: true

